import type { Metadata } from 'next'
import styles from './layout.module.scss'
import NavBar from '@/components/common/nav-bar/NavBar'
import SideBar from '@/components/common/side-bar/SideBar'
import Footer from '@/components/display/Footer/Footer'

export const metadata: Metadata = {
  title: 'Good Games || Home',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={styles.container}>
      <div className={styles.nav}>
        <NavBar />
      </div>
      <div className={styles.sidebar}>
        <SideBar />
      </div>
      <div className={styles.content}>{children}</div>
      <div className={styles.footer}>
        <Footer />
      </div>
    </div>
  )
}
