import type { Metadata } from 'next'
import { Inter, Nova_Square, Poppins } from 'next/font/google'
import './globals.scss'
import SideBar from '@/components/common/side-bar/SideBar'
import NavBar from '@/components/common/nav-bar/NavBar'
import styles from './layout.module.scss'
import Footer from '@/components/display/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })
const Nova = Nova_Square({ subsets: ['latin'], weight: '400' })
const Pop = Poppins({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Good Games',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={styles.html}>
      <head>
        <link rel="icon" href="/public/global-logo.png" />
      </head>
      <body suppressHydrationWarning={true} className={`${Pop.className} `}>
        {/* <div className={styles.nav}>
          <NavBar />
        </div>
        <div className={styles.sidebar}>
          <SideBar />
        </div>
        <div className={styles.footer}>
          <Footer />
        </div> */}

        {/* <div className={styles.content}>{children}</div> */}
        {children}
      </body>
    </html>
  )
}
