import type { Metadata } from "next";
import { Inter, Nova_Square } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const Nova = Nova_Square({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Good Games",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Nova.className}>{children}</body>
    </html>
  );
}
