import type { Metadata } from 'next'
import styles from './layout.module.scss'
import Footer from '@/components/display/Footer/Footer'
import SideBar from '@/components/common/side-bar/SideBar'

export const metadata: Metadata = {
  title: 'Good Games || Profile',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={styles.container}>
      <div className={styles.sidebar}>
        <SideBar />
      </div>
      <div className={styles.content}>{children}</div>
      <div className={styles.footer}>
        <Footer />
      </div>
    </div>
  )
}
